<a href="https://colab.research.google.com/github/NewbieZilani/MSc-Explainable-AI/blob/main/01_NumPy/01_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [2]:
marks = np.array([85, 72, 90, 65, 88, 92, 75, 80, 95, 70])
print(marks)

[85 72 90 65 88 92 75 80 95 70]


In [6]:
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))

81.2
95
65
812


In [7]:
marks2d = np.array([
    [80,70,90,60],
    [75,85,88,91],
    [95,90,92,94],
    [60,65,70,68],
    [88,84,82,80]
])

print(marks2d)

[[80 70 90 60]
 [75 85 88 91]
 [95 90 92 94]
 [60 65 70 68]
 [88 84 82 80]]


In [10]:
# row=student, column=subject
# all marks for 1 student
print(marks2d[0])
print(marks2d[1])

[80 70 90 60]
[75 85 88 91]


In [12]:
# all student for 1 subject
print(marks2d[:,0])
print(marks2d[:,3])

[80 75 95 60 88]
[60 91 94 68 80]


In [15]:
# 1 subject for 1 student
print(marks2d[2,2])
print(marks2d[3,1])

92
65


In [17]:
# average for 1 student
print(np.mean(marks2d[0]))
print(np.mean(marks2d[2]))

75.0
92.75


In [19]:
# average for all students
print(np.mean(marks2d, axis=1))
# average for single subject
print(np.mean(marks2d, axis=0))

[75.   84.75 92.75 65.75 83.5 ]
[79.6 78.8 84.4 78.6]
